import { Header } from '@/Components/Header'
import { Nunito } from 'next/font/google'
import './globals.css'
import { GitHubProvider } from '@/context/GithubContext'

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito'
})


export const metadata = {
  title: 'GitHub Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${nunito.variable}`}>
      <body className='bg-[#071422] mb-56'>
        <GitHubProvider>
          <Header/>
          {children}
        </GitHubProvider>
      </body>
    </html>
  )
}
